name: Go CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5 
        with:
          go-version: '1.23.5'

      - name: Build
        run: go build ./... 

      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
          total_coverage=$(go tool cover -func=coverage.out | grep total: | awk '{print substr($3, 1, length($3)-1)}')
          echo "Total coverage: $total_coverage%"
          min_coverage=75.0
          result=$(echo "$total_coverage >= $min_coverage" | bc -l)
          if [ "$result" -ne 1 ]; then
            echo "❌ Code coverage $total_coverage% is below required $min_coverage%"
            exit 1
          else
            echo "✅ Code coverage $total_coverage% meets minimum $min_coverage%"
          fi
